### ISSUE TITLE
Again, not an issue, just a question

### ISSUE THREAD

**Issue by Theremingenieur** [wagiminator/SAMD-Development-Boards#3]
Hi Stefan,

I was looking around on most maker platforms because I wanted to buy your SAMD-Programmer-Adapter boards, already built and ready to use. But I could not find them. Do you have an indication?

**Comment by wagiminator** [comment]
Hi, I don't sell any boards. If you're looking for a programmer, Alex Taradov sells his boards: https://www.tindie.com/products/ataradov/cmsis-dap-compliant-swd-debugger/.

**Comment by Theremingenieur** [comment]
Thank you for your reply. I have a programmer and was looking into your nifty adapter board collection with the ZIF sockets.
